apiVersion: apps/v1
kind: Deployment
metadata:
  name: equipmentinventory-deployment
spec:
  selector:
    matchLabels:
      app: equipmentinventory
  template:
    metadata:
      labels:
        app: equipmentinventory
        azure.workload.identity/use: "true" 
    spec:
      serviceAccountName: equipmentinventory-serviceaccount
      containers:
      - name: equipmentinventory
        image: harvesthelper.azurecr.io/harvesthelper.equipmentinventory:1.0.4
        env:
          - name: ServiceSettings__MessageBroker
            value: SERVICEBUS
          - name: ServiceSettings__KeyVaultName
            value: harvesthelper
          - name: ServiceSettings__Authority
            value: https://harvesthelper.westeurope.cloudapp.azure.com/identity-svc
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 5004
        livenessProbe: 
          httpGet:
            path: /health/live
            port: 5004
          initialDelaySeconds: 10
        readinessProbe: 
          httpGet:
            path: /health/ready
            port: 5004
          initialDelaySeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: equipmentinventory-service
spec:
  type: ClusterIP
  selector:
    app: equipmentinventory
  ports:
    - port: 80
      targetPort: 5004

---
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: equipmentinventory-serviceaccount
  annotations: 
    azure.workload.identity/client-id: f7610b14-5c9b-4830-8fd1-e0909e823f9b
  labels: 
    azure.workload.identity/use: "true"