microserviceName : "equipmentinventory"

image: 
  repository: harvesthelper.azurecr.io/harvesthelper.equipmentinventory
  tag: 1.0.4

envVariables:
   ServiceSettings__Authority: https://harvesthelper.westeurope.cloudapp.azure.com/identity-svc

resources:
  limits:
    memory: "128Mi"
    cpu: "150m"

container:
  port: 5004

identityClientId: f7610b14-5c9b-4830-8fd1-e0909e823f9b