microserviceName : "equipmentinventory"

image: 
  repository: harvesthelper.azurecr.io/harvesthelper.equipmentinventory
  tag: 1.0.4

envVariables:
   ServiceSettings__Authority: https://harvesthelper.westeurope.cloudapp.azure.com/identity-svc

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"

container:
  port: 5004

identityClientId: 62e2f026-1aba-488f-87e3-f5487e4e0125